### ISSUE TITLE
Converting to 16x2 and Uno

### ISSUE THREAD

**Issue by tpmassa** [cgmckeever/force-resistance-arduino#4]
I have altered the code to work with a 16x2 and Uno.  Just a few questions. 

1. What is the polling for?  Is this for screen timeouts?
2. How does the calibration work?  I assume trial and error - changing the value of maxV to match 100 resistance?
3. What are button A, B and C used for?  
4. When printing I got "=" after each word - except it was four lines on top of each other not two.  Do you know why?  I ended up adding a blank string after to avoid this. 

Thanks so much.  I plan to make this a christmas gift for my wife.  My code is below:

// config
#include "config.h"

//LCD Library
#include <Wire.h>
#include <LiquidCrystal_I2C.h>
LiquidCrystal_I2C lcd(0x27, 16, 2);

bool displayOn = false;

int fsrLevel = 0;
int fsrNormalized = 0;
int fsrLast = 0;
int fsrReadings = fsrMaxReadings;
int fsrNoChange = 0;

int sleepPolls = 0;

void print(const char *line1, const char *line2);

void setup() {
  Serial.begin(115200);
  Serial.println("");
  Serial.println("Booting...");

  activate();

  pinMode(BUTTON_A, INPUT_PULLUP);
  pinMode(BUTTON_B, INPUT_PULLUP);
  pinMode(BUTTON_C, INPUT_PULLUP);
}

void loop() {
  if(!digitalRead(BUTTON_A)) calibrate();
  if(!digitalRead(BUTTON_B)) displayToggle();
  if(!digitalRead(BUTTON_C)) reduceReadingInterval();

  getResistance();
  if (displayOn) {
    if (fsrNoChange > sleepPolls) displayToggle();
  } else if (fsrNormalized > 80) displayToggle();
}

void getResistance() {
  int fsrTotal = 0;

  for(int i = 1; i <= fsrReadings; i++) {
    fsrTotal += analogRead(fsrPin);
    delay(pollingInterval);
  }

  fsrLevel = floor(fsrTotal / fsrReadings);
  Serial.print("Analog reading = ");
  Serial.println(fsrLevel);

  fsrNormalized = floor(100 * fsrLevel / maxV);
  if (fsrNormalized > 100) fsrNormalized = 100;

  String s = String(fsrNormalized);
  print("Resistance", s.c_str());

  int increment = fsrNormalized == fsrLast ? 1 : 0;
  fsrNoChange += increment;
  fsrLast = fsrNormalized;
}

void setSleepPolls() {
  int pollMS = (pollingInterval * fsrReadings);
  sleepPolls = 1000 * secondsTillSleep / pollMS;
  fsrNoChange = 0;

  Serial.print("Sleep Polls: ");
  Serial.println(sleepPolls);
}

void calibrate() {
  int minV = analogRead(fsrPin);
  printCalibration();
  print("Hold Break", "5 seconds");
  delay(3000);

  maxV = analogRead(fsrPin) - minV;
  printCalibration();
}

void reduceReadingInterval() {
  if (fsrReadings > 1) {
   fsrReadings -= 1;
  } else {
    fsrReadings = fsrMaxReadings;
  }

  setSleepPolls();
  printInterval();
}

int centerText(const char *buf) {
  int16_t x1, y1;
  uint16_t w, h;
 
  return 0;
}

void printAt(String text, int X, int Y) {
  text = "    " + text + "          ";
  lcd.setCursor(X, Y);
  lcd.println(text);
  lcd.display();
}

void print(const char *line1, const char *line2 = "") {
  if (displayOn) {
    lcd.clear();

    int x = centerText(line1);
    printAt(line1, 0, 0);

    x = centerText(line2);
    printAt(line2, 5, 1);
  }
}

void printCalibration() {
  String s = "max: " + String(maxV);
  print("Calibrate", s.c_str());
  delay(2000);
}

void printInterval() {
  String s = "-- " + String(fsrReadings) + " --";
  print("Polling", s.c_str());
  delay(2000);
}

void activate() {
  lcd.begin();
  lcd.backlight();
  displayOn = true;
  Serial.println("Screen on");

  print("DIYPELOTON");
  delay(200);
  printCalibration();
  setSleepPolls();
  printInterval();
}

void displayToggle() {
  if (displayOn) {
    activate();
    Serial.println("Sleep Activated");
    print("Goodbye...");
    delay(2000);
    lcd.clear();
    lcd.display();
    lcd.noBacklight();
    displayOn = false;
  } else {
    activate();
  }
}

**Comment by cgmckeever** [comment]
**What is the polling for? Is this for screen timeouts?**

The polling interval is so the device just isnt constantly taking a reading. Just lets it sleep for a moment .. I think that was what you were asking?

**How does the calibration work? I assume trial and error - changing the value of maxV to match 100 resistance?**

If I remember, you put it in calibration mode and just jam the stop pad down as much as possible. Mine is a push-knob so I just push down on that. In my brain, that will be the 'largest' pressue, and therefore 100. However, the actual resistance is not linear (from my understanding of others discussion about these force sensitive resistors). So at the end of the day this method gives you the 100 level, but every thing in between is 'feel'

**What are button A, B and C used for?**

My device (HuzzahFeather) had 3 buttons, They can be configured for anything by default 

```
if(!digitalRead(BUTTON_A)) calibrate();
if(!digitalRead(BUTTON_B)) displayToggle();
if(!digitalRead(BUTTON_C)) reduceReadingInterval();
```

A = calibration mode
B = Turns the display off
C = changes the normalization of the readings (how many readings it averages before determining current level)


**When printing I got "=" after each word - except it was four lines on top of each other not two. Do you know why? I ended up adding a blank string after to avoid this.**

This may be something with the display./encoding ... your solution is probably where I'd land

**Comment by tpmassa** [comment]
Thank you for your help.  This clears things up.
